// Creates license badge depending on which one is used.
// If there is no license or user selects "unlicensed", this returns an empty string
// Note to graders, I did not see a point in seperate functions for generating the license
// section, as well as one that generates the badge link seperately. I have removed both of these
// TO DO functions from the starter code.
function renderLicenseBadge(license) {
  if (license == 'Apache') {
    licenseBadge = '[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)' 
  }
  else if ((license == 'General-Public-License (3.0)')){
    licenseBadge = '[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)'
  }
  else if ((license == 'MIT')){
    licenseBadge = '[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)'
  }
  else if ((license == 'Mozilla-Public')){
    licenseBadge = '[![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg)](https://opensource.org/licenses/MPL-2.0)'
  }
  // Also covers for Unlicensed selection
  else {
    licenseBadge = ''
  }
  return licenseBadge;
}

// Generates Markdown for README
// Table of contents is generated by default since required sections are known.
function generateMarkdown(data) {
  let badge = renderLicenseBadge(data.licensing);
  console.log(badge);
  return `# ${data.title}

  ## Licensing:
  ${badge}
  ## Table of Contents 
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [Contribution](#contribution)
  - [Testing](#testing)
  - [Questions](#questions)
  ## Description:
  ${data.description}
  ## Installation:
  ${data.installation}
  ## Usage:
  ${data.usage}
  ## License:
  This is Licensed under the ${data.licensing} License. Copyright 2022.
  ## Contribution:
  ${data.contribution}
  ## Testing:
  ${data.testing}
  ## Questions:
  - Github: [${data.github}](https://github.com/${data.github})
  - Email: ${data.email}`;
}

module.exports = generateMarkdown;
